# Generated by Django 4.2.6 on 2023-11-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(default=1676626, max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_type', models.CharField(choices=[('savings', 'savings'), ('current', 'current'), ('salary', 'salary')], default='', max_length=20)),
            ],
        ),
    ]
