# Generated by Django 4.2.6 on 2023-11-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=2336764, max_length=10, primary_key=True, serialize=False),
        ),
    ]
